### ISSUE TITLE
bad request on submitting new member

### ISSUE THREAD

**Issue by mahmmoudkinawy** [mahmmoudkinawy/Media-Application#2]
- This bug not from the API it's from angular

**Comment by mkinawy** [comment]
I will have a look later, where in the code does this happen?

**Comment by mahmmoudkinawy** [comment]
This bug happens here at 
https://localhost:4200/ 
when new user register to our app.

**Comment by mahmmoudkinawy** [comment]
Here 
client\src\app\register
